# Generated by Django 5.1.1 on 2024-09-18 15:20

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "deadline",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            9,
                            18,
                            15,
                            20,
                            50,
                            990998,
                            tzinfo=datetime.timezone.utc,
                        ),
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.datetime(
                                    2024,
                                    9,
                                    18,
                                    15,
                                    20,
                                    50,
                                    991008,
                                    tzinfo=datetime.timezone.utc,
                                )
                            )
                        ],
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Todo",
                "verbose_name_plural": "Todos",
                "ordering": ["deadline"],
            },
        ),
    ]
