# Generated by Django 5.1.1 on 2024-09-18 20:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 18, 20, 41, 38, 853919, tzinfo=datetime.timezone.utc
                ),
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2024,
                            9,
                            18,
                            20,
                            41,
                            38,
                            853929,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
            ),
        ),
    ]
