# Generated by Django 5.1.1 on 2024-09-07 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todomodel",
            name="deadline",
            field=models.DateField(
                default=datetime.datetime(2024, 9, 7, 15, 8, 13, 424395)
            ),
        ),
    ]
