# Generated by Django 5.1.1 on 2024-09-07 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_alter_todomodel_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="deadline",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 7, 11, 47, 7, 79696, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
