# Generated by Django 5.1.1 on 2024-09-07 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0006_alter_todomodel_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todomodel",
            options={
                "ordering": ["deadline"],
                "verbose_name": "Todo",
                "verbose_name_plural": "Todos",
            },
        ),
        migrations.AlterField(
            model_name="todomodel",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 7, 11, 52, 35, 40579, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
